### ISSUE TITLE
Error with simple route setup

### ISSUE THREAD

**Issue by seangates** [patrick-steele-idem/meta-router#12]
I'm currently using a set of simple routes, but getting an error with the meta-router. My `routes.json` is as follows:

```json
[
  {
    "path": "GET /sh/waitlist",
    "handler": "require:./src/pages/waitlist"
  },
  {
    "path": "GET /sh",
    "handler": "require:./src/pages/index"
  },
  {
    "path": "GET /",
    "handler": "require:./src/pages/index"
  }
]
```

And, here is the error I get:

```
TypeError: Property '0' of object [object Object] is not a function
   at next (/Users/sgates/Development/feshhome/node_modules/meta-router/lib/Route.js:21:30)
   at /Users/sgates/Development/feshhome/node_modules/meta-router/lib/Route.js:25:9
   at invokeHandler (/Users/sgates/Development/feshhome/node_modules/meta-router/middleware/invokeHandler.js:17:13)
   at invokeHandler (eval at createToggleWrapper (/Users/sgates/Development/feshhome/node_modules/kraken-js/node_modules/meddleware/index.js:133:51), <anonymous>:1:74)
   at Layer.handle [as handle_request] (/Users/sgates/Development/feshhome/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:312:13)
   at /Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:271:10)
   at oAuth (/Users/sgates/Development/feshhome/node_modules/oauth-ebay/lib/middleware/index.js:49:9)
   at oAuth (eval at createToggleWrapper (/Users/sgates/Development/feshhome/node_modules/kraken-js/node_modules/meddleware/index.js:133:51), <anonymous>:1:66)
   at Layer.handle [as handle_request] (/Users/sgates/Development/feshhome/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:312:13)
   at /Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/sgates/Development/feshhome/node_modules/express/lib/router/index.js:271:10)
```

I've tried everything I can think of to get the route to work, but each time I get the same error.

**Comment by patrick-steele-idem** [comment]
Hi @seangates, which version of `meta-router` are you using? We probably need to adjust the error reporting a bit.

Also, I would recommend upgrading to the latest major version. The latest version also comes with a simpler syntax:

```javascript
[
  "GET /sh/waitlist => ./src/pages/waitlist",
  "GET /sh => ./src/pages/index",
  "GET / => ./src/pages/index"
]
```

Let me know which version so I can take a closer look.

Thanks,
Patrick

**Comment by seangates** [comment]
My package.json has the following `"meta-router": "^2"`.

**Comment by patrick-steele-idem** [comment]
@seangates, can you try `npm install meta-router@3 --save`

You won't need to change your code at all despite the major version change.

**Comment by seangates** [comment]
Okay, giving it a try.

**Comment by seangates** [comment]
Same error as above.

**Comment by patrick-steele-idem** [comment]
What is being exported by `./src/pages/waitlist/index.js`? Are you sure that module is exporting a handler function using code similar to the following?:

```javascript
module.exports = function(req, res) { ... }
```

In the mean time I will add better error reporting.

**Comment by seangates** [comment]
This is everything in the index.js file at that path:

```
'use strict';

var templatePath = require.resolve('./index.marko');
var template = require('marko').load(templatePath);

exports.renderer = function (data, context) {
  template.render(data, context);
};
```

**Comment by patrick-steele-idem** [comment]
The handler needs to be a middleware function:

```javascript
module.exports = function(req, res) { ... }
```

It looks like the bug is in your code. Correct?

**Comment by seangates** [comment]
Interesting. This project is modeled after a similar project. I'm wondering if it got removed en transit. I will refactor and let you know.

**Comment by seangates** [comment]
That worked. Thanks for your help!
